package appswing.components;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.LinearGradientPaint;
import java.awt.geom.Point2D;

public class Model extends javax.swing.JPanel {

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2d = (Graphics2D) g;

        // Definindo as cores do arco-íris em tons suaves
        Color[] colors = {
                new Color(255, 182, 193), // Rosa claro
                new Color(255, 192, 203), // Rosa bebê
                new Color(255, 218, 185), // Pêssego
                new Color(255, 250, 205), // Limão
                new Color(173, 216, 230), // Azul claro
                new Color(230, 230, 250) // Lavanda
        };

        // Frações para o gradiente (distribuição das cores)
        float[] fractions = { 0.0f, 0.2f, 0.4f, 0.6f, 0.8f, 1.0f };

        // Cria um gradiente linear com as cores definidas
        LinearGradientPaint gp = new LinearGradientPaint(
                new Point2D.Float(0, 0),
                new Point2D.Float(getWidth(), getHeight()),
                fractions,
                colors);

        // Aplica o gradiente
        g2d.setPaint(gp);
        g2d.fillRect(0, 0, getWidth(), getHeight());
    }

    public Model() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 800, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 600, Short.MAX_VALUE));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
